import type { ProviderId } from '~/types'

/**
 * Input parts used to derive a stable completion cache key.
 */
export interface CompletionCacheKeyParts {
  provider: ProviderId
  model: string
  prefix: string
  suffix?: string
  context?: string
}

/**
 * Default upper bound for in-memory completion cache entries.
 *
 * Use when:
 * - creating the standard short-lived in-memory cache
 * - aligning local persistent cache heuristics with the same capacity assumptions
 *
 * Returns:
 * - the default maximum entry count
 */
export const DEFAULT_COMPLETION_CACHE_MAX_ENTRIES = 50

/**
 * Default time-to-live for completion cache entries in milliseconds.
 *
 * Use when:
 * - creating the standard short-lived completion cache
 * - reusing the same expiry policy for persisted cache rows
 *
 * Returns:
 * - the default cache TTL in milliseconds
 */
export const DEFAULT_COMPLETION_CACHE_TTL_MS = 15_000

interface CacheEntry {
  value: string
  expiresAt: number
}

/**
 * Builds the in-memory completion cache key from request identity fields.
 *
 * Before:
 * - `{ provider: "groq", model: "llama", prefix: "hello", suffix: "", context: "" }`
 *
 * After:
 * - `"groq␟llama␟hello␟␟"`
 */
export function buildCompletionCacheKey(parts: CompletionCacheKeyParts): string {
  return [
    parts.provider,
    parts.model,
    parts.prefix,
    parts.suffix ?? '',
    parts.context ?? '',
  ].join('\u241F')
}

/**
 * Small in-memory completion cache with TTL expiry and recency refresh.
 *
 * Use when:
 * - repeated identical completion requests should avoid another background round-trip
 * - only the most recent small set of completions should be kept in memory
 *
 * Expects:
 * - callers to provide stable keys generated by `buildCompletionCacheKey`
 *
 * Returns:
 * - a cache instance with `get` and `set` operations
 */
export class CompletionMemoryCache {
  private readonly entries = new Map<string, CacheEntry>()

  constructor(
    private readonly maxEntries = DEFAULT_COMPLETION_CACHE_MAX_ENTRIES,
    private readonly ttlMs = DEFAULT_COMPLETION_CACHE_TTL_MS,
  ) {}

  get(key: string, now = Date.now()): string | null {
    const entry = this.entries.get(key)
    if (!entry)
      return null
    if (entry.expiresAt <= now) {
      this.entries.delete(key)
      return null
    }

    // Refresh recency for a tiny LRU-like behavior.
    this.entries.delete(key)
    this.entries.set(key, entry)
    return entry.value
  }

  set(key: string, value: string, now = Date.now()): void {
    if (!value)
      return
    if (this.entries.has(key)) {
      this.entries.delete(key)
    }
    this.entries.set(key, {
      value,
      expiresAt: now + this.ttlMs,
    })
    this.evictOverflow()
  }

  private evictOverflow(): void {
    while (this.entries.size > this.maxEntries) {
      const oldestKey = this.entries.keys().next().value
      if (oldestKey === undefined)
        return
      this.entries.delete(oldestKey)
    }
  }
}
